import { Usuario } from './usuario.model';
import { Err } from './error.model';
// Generated by https://quicktype.io

export interface UsuarioResponse {
  exito: boolean;
  usuarios: Usuario[];
  token: string;
  err: Err;
}
