// Generated by https://quicktype.io

export interface Usuario {
   
    uid ?:    string;
    estado: boolean;
    nombre: string;
    role:   string;
    google : boolean ;
    email :  string;
    img ?: string;
    password ?: string;
    
}
